require('alexesba.base')
require('alexesba.lazy')
--[[ require('alexesba.packer.bootstrap')
require('alexesba.packer.plugins') ]]
require('alexesba.functions')
require('alexesba.commands')
require('alexesba.mappings')
require('alexesba.augroups')
require('alexesba.statusLine')
require('alexesba.linters')
require('alexesba.utils.autoreload')
