require('alexesba.linters.cssls')
require('alexesba.linters.cucumber')
require('alexesba.linters.elixir')
require('alexesba.linters.eslint')
require('alexesba.linters.grammar-guard')
-- require('alexesba.linters.grammarly')
require('alexesba.linters.html')
require('alexesba.linters.jsonls')
require('alexesba.linters.lualanguageserver')
-- require('alexesba.linters.remark_ls')
require('alexesba.linters.solargraph')
require('alexesba.linters.sqlls')
require('alexesba.linters.stylelint_lsp')
-- require('alexesba.linters.tailwindcss')
require('alexesba.linters.tsserver')
