return {
  { 'aca/marp.nvim',             ft = { 'md', 'markdown' } },
  { 'andymass/vim-matchup' },
  { 'dhruvasagar/vim-table-mode' },
  { 'dietsche/vim-lastplace' },
  { 'godlygeek/tabular' },
  { 'kopischke/vim-fetch' },
  { 'mg979/vim-visual-multi' },
  { 'rorymckinley/vim-rubyhash', ft = { 'erb', 'ruby' } },
  { 'skywind3000/asyncrun.vim' },
  { 'tpope/vim-abolish' },
  { 'tpope/vim-bundler' },
  { 'tpope/vim-dispatch' },
  { 'tpope/vim-eunuch' },
  { 'tpope/vim-fugitive' },
  { 'tpope/vim-repeat' },
  { 'tpope/vim-surround' },
  { 'AndrewRadev/tagalong.vim', ft = { 'javascriptreact', 'html', 'eruby', 'haml', } },
}
