--[[ require('glinters.cssls')
require('linters.elixir') ]]
require('linters.eslint')
-- require('linters.grammar-guard')
-- require('linters.grammarly')
-- require('linters.html')
require('linters.jsonls')
require('linters.lua_ls')
-- require('linters.remark_ls')
-- require('linters.solargraph')
require('linters.ruby-lsp')
-- require('linters.sqlls')
require('linters.stylelint_lsp')
-- require('linters.tailwindcss')
require('linters.tsserver')
-- require('linters.yamlls')
-- require('linters.emmet')
